export const ADMIN_LINKS = [
  { href: "/admin", label: "لوحة التحكم" },
  { href: "/admin/navbar", label: "القائمة" },
  { href: "/admin/footer", label: "تذييل الصفحة" },
  { href: "/admin/origin", label: "أصل آل سوبره" },
  { href: "/admin/family-tree", label: "شجرة العائلة" },
  { href: "/admin/annual-iftar", label: "الافطرات السنوية" },
  { href: "/admin/academic-trip", label: "الرحلات الثقافية" },
  { href: "/admin/grad-commencements", label: "حفلات التخرج" },
  { href: "/admin/honoring", label: "تكريم" },
  { href: "/admin/internal-rules", label: "النظام الداخلي" },
  { href: "/admin/rules", label: "النظام الاساسي" },
  { href: "/admin/administration", label: "الهيئة الادارية" },
  { href: "/admin/family-guide", label: "دليل العائلة" },
  { href: "/admin/images", label: "البوم الصور" },
  { href: "/admin/street-ceremony", label: "افتتاح شارع" },
  { href: "/admin/donate", label: "التبرع" },
  { href: "/admin/contact", label: "اتصل بنا" },
  { href: "/admin/notification-center", label: "الاشعارات" },
];
